# Generated by Django 5.1.4 on 2025-01-27 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('896aa6b1-6a70-47fc-ad75-b521366956bd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='type',
            field=models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports'), ('Education', 'Education'), ('Technology', 'Technology'), ('Art', 'Art'), ('Theater', 'Theater'), ('Food', 'Food'), ('Fitness', 'Fitness'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Business', 'Business'), ('Health', 'Health'), ('Literature', 'Literature'), ('Science', 'Science'), ('History', 'History')], max_length=25),
        ),
    ]
