# Generated by Django 5.1.4 on 2025-01-29 01:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_eventmodel_id_alter_eventmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d424f45-3bb9-4348-867b-0907f5c03334'), primary_key=True, serialize=False, unique=True),
        ),
    ]
