# Generated by Django 5.1.4 on 2025-01-29 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_eventmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('26b0ef1e-cd7c-41d0-be2a-149f28378c1c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
