# Generated by Django 5.1.4 on 2025-01-30 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_eventmodel_view_alter_eventmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('918e9470-55dc-496e-9b16-d1d278682bb4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
