# Generated by Django 5.1.4 on 2025-01-30 11:27

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_alter_eventmodel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boximage',
            name='id_user',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='events',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='map_ifram',
            field=models.CharField(max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='boximage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
