# Generated by Django 5.1.4 on 2025-01-31 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_boximage_id_user_eventmodel_events_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_one',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_one_describe',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_one_thumb_png',
            field=models.ImageField(null=True, upload_to='joiner_img'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_three',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_three_describe',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_three_thumb_png',
            field=models.ImageField(null=True, upload_to='joiner_img'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_two',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_two_describe',
            field=models.CharField(default='', max_length=266),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='joiner_two_thumb_png',
            field=models.ImageField(null=True, upload_to='joiner_img'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='events',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
