# Generated by Django 5.1.4 on 2025-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_rename_descrbe_two_eventmodel_describe_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
