# Generated by Django 5.1.4 on 2025-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Event", "0011_eventmodel_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("Music", "Music"),
                    ("Sports", "Sports"),
                    ("Education", "Education"),
                    ("Technology", "Technology"),
                    ("Art", "Art"),
                    ("Theater", "Theater"),
                    ("Food", "Food"),
                    ("Fitness", "Fitness"),
                    ("Travel", "Travel"),
                    ("Fashion", "Fashion"),
                    ("Business", "Business"),
                    ("Health", "Health"),
                    ("Literature", "Literature"),
                    ("Science", "Science"),
                    ("History", "History"),
                    ("Game", "Game"),
                ],
                max_length=25,
            ),
        ),
    ]
