# Generated by Django 5.1.4 on 2025-02-16 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0012_alter_eventmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='price',
        ),
    ]
