# Generated by Django 5.1.4 on 2025-02-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0013_remove_eventmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=266),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=266),
        ),
    ]
