# Generated by Django 5.1.4 on 2025-02-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0014_alter_eventmodel_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='locate',
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='address',
            field=models.CharField(blank=True, max_length=266),
        ),
    ]
