# Generated by Django 4.2 on 2025-02-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0015_remove_eventmodel_locate_alter_eventmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='map_ifram',
        ),
    ]
