# Generated by Django 5.1.4 on 2025-02-08 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(default='', max_length=266)),
                ('title', models.CharField(max_length=256, null=True)),
                ('describe', models.CharField(max_length=256, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
