# Generated by Django 5.1.4 on 2025-02-12 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCheckEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('event_id', models.UUIDField(default='')),
                ('user_id', models.UUIDField(default='')),
            ],
        ),
    ]
