# Generated by Django 5.1.4 on 2025-02-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_qrcheckevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcheckevent',
            name='da_tham_gia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcheckevent',
            name='qr_img',
            field=models.ImageField(null=True, upload_to='qr-code'),
        ),
    ]
