# Generated by Django 4.2 on 2025-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0003_qrcheckevent_da_tham_gia_qrcheckevent_qr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcheckevent',
            name='qr_img',
            field=models.ImageField(null=True, upload_to='qr-codes/'),
        ),
    ]
